<?php

namespace App\Http\Middleware;

use App\Models\Task;
use App\Services\TaskTokenService;
use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Symfony\Component\HttpFoundation\Response;

/**
 * Authenticate requests using a task-scoped HMAC bearer token.
 *
 * The executor sends `Authorization: Bearer <token>` where the token was
 * generated by TaskTokenService at dispatch time (T18). This middleware
 * validates the token's HMAC signature, expiry, and task ID binding.
 *
 * On success, the resolved Task model is merged into the request as
 * `validated_task` so the controller can use it directly.
 *
 * @see \App\Services\TaskTokenService
 * @see §20.4 Runner Result API
 */
class AuthenticateTaskToken
{
    public function __construct(
        private readonly TaskTokenService $taskTokenService,
    ) {}

    public function handle(Request $request, Closure $next): Response
    {
        $bearerToken = $request->bearerToken();

        if ($bearerToken === null || $bearerToken === '') {
            Log::warning('Task result request missing bearer token', [
                'ip' => $request->ip(),
            ]);

            return response()->json(['error' => 'Missing task token.'], 401);
        }

        /** @var Task $task */
        $task = $request->route('task');

        if (! $this->taskTokenService->validate($bearerToken, $task->id)) {
            Log::warning('Task result request with invalid token', [
                'task_id' => $task->id,
                'ip' => $request->ip(),
            ]);

            return response()->json(['error' => 'Invalid or expired task token.'], 401);
        }

        // Make the authenticated task available to the controller
        $request->merge(['validated_task' => $task]);

        return $next($request);
    }
}
